### ISSUE TITLE
Allow users to modify RStudio Connect index.html file

### ISSUE THREAD

**Issue by GShotwell** [rstudio/pins#159]
We're releasing some wrappers around pins for internal use, and we wanted to change the material which is printed in the Rstudio Connect gui, so that it would recommend our wrappers rather than `pin_get`. 

I did this in a fairly simple way by allowing the user to point to a different index.html file  which I'm happy to submit in a pull request if it's helpful: https://github.com/GShotwell/pins/blob/master/R/board_rsconnect_bundle.R#L4-L9

Another option for solving this problem might include some kind of pins/Rmarkdown hybrid (pindown) whereby the Rmarkdown was rendered as the front matter for the pin. This is probably more use friendly, but also a bit more complicated.

**Comment by javierluraschi** [comment]
Yes, feel free to send that PR!

However, there is a not-yet-documented feature you might like, maybe...

So `pins` supports output files with RStudio Connect as well, so you can create the following R Markdown file:

``````
---
title: "pin-output"
output: html_document
---

# Pin using Output Files

```{r}
pins::board_register("rsconnect", output_files = TRUE)
pins::pin(iris, "iris" board = "rsconnect")
```

Check out the iris pin under: [iris/](iris/).
``````

Which you can then publish to connect, in connect it will render as:

<img width="1046" alt="Screen Shot 2020-01-16 at 5 02 39 PM" src="https://user-images.githubusercontent.com/3478847/72575676-0d675080-3882-11ea-9c86-75c2505b2248.png">

You can then follow the link or open with "Open Solo" and add the name of the pin to the URL, as in, https://connect-server/content/content-id/iris/, to arrive to the actual pin:

<img width="1080" alt="Screen Shot 2020-01-16 at 5 02 50 PM" src="https://user-images.githubusercontent.com/3478847/72575735-34258700-3882-11ea-8b34-5b954474d0ed.png">

You can then still download the pin as follows:

```
pins::pin_get("https://rstudio-connect-server/content/app-id/iris", board = "rsconnect")
```
```
# A tibble: 150 x 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>  
 1          5.1         3.5          1.4         0.2 setosa 
 2          4.9         3            1.4         0.2 setosa 
 3          4.7         3.2          1.3         0.2 setosa 
 4          4.6         3.1          1.5         0.2 setosa 
 5          5           3.6          1.4         0.2 setosa 
 6          5.4         3.9          1.7         0.4 setosa 
 7          4.6         3.4          1.4         0.3 setosa 
 8          5           3.4          1.5         0.2 setosa 
 9          4.4         2.9          1.4         0.2 setosa 
10          4.9         3.1          1.5         0.1 setosa 
# … with 140 more rows
```

(( Make sure to replace `rstudio-connect-server` and `app-id` with the correct values )).

This is not documented since is quite advanced, but if you find this useful, we'll add an entry in the official docs explaining this properly.
