### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/pins#178]
Properly support dataset versions

Some boards like GitHub, Kaggle and RStudio Connect support dataset versions; however, there is no way to retrieve an specific version from pins, turn off this functionality, or support versions in other boards like local, S3, azure and Google Cloud.

**Comment by cboettig** [comment]
I think this is great, but I'd love a deeper discussion of what exactly `pins` will mean by "a version".  Is a version an immutable set of content or just a label?  Can we "delete" old versions, and what does that mean for the package API?

Note that GitHub supports both immutable and mutable "versions": 'committed' objects are pretty-much immutable, since git is essentially a content-addressed storage mechanism.  But "releases" are just labels, we can technically overwrite a release attribute (even though the `pins` interface doesn't support this).  Overwriting labels can be valuable -- working with dynamically changing large files we can easily end up consuming tons of storage we don't actually care about.  

I think any versioning mechanism needs to consider garbage collection / overwrite ability in some way. (`pins` currently ignores this entirely on GitHub versioning -- I realize that storage is "free" and permissible but I'm not sure how I feel about treating it as inexhaustible)


I think a generic content-based-address model could a very compelling way to implement data versioning, which could work across S3 and other backends.  But this is also well-trodden ground and it might be worth looking at prior art (see dat, IPFS, and hash-archive.org and other projects).

**Comment by javierluraschi** [comment]
I'm thinking versions need to be immutable, since neither datasets in Kaggle, RStudio Connect nor GitHub commits are mutable.

The challenge with GitHub releases is that they are mostly a hack for datasets, while GitHub encourages using them for large files, they are completely detached from the usual GitHub workflow like PR's, commits, diffs, etc. However, I do think that is valuable to turn off versioning for GitHub boards such that, advanced users like you, can then use pins to upload datasets with appropriate labels as GitHub release files.

So I'd expect you would be interested to register in GitHub like:

```
board_register_github("repo", version = FALSE)
```

Then `pin()` would not add a tag to the GitHub release file... I'm planning to work on this next week... so maybe easier to write some code and ask for feedback afterwards.

**Comment by cboettig** [comment]
Cool!  In principle I think you could implement (immutable) versioning just as easily on S3 (e.g. with a content-addressed system).  I think the main reason not to do so is it could make the cost of S3 storage grow pretty quickly with large datasets -- or some way to manage garbage collection of old versions would be needed? It seems it would be desirable for the pins interface to be as consistent as possible across backends, right?

**Comment by javierluraschi** [comment]
Great point! So we should definitely make this customizable... so maybe there is a `max_versions` parameter to remove older versions whenever a new version is added... but yeah, maybe the default should be "whatever the board supports". For GitHub, Kaggle, and RStudio Connect you get versions for free so they are enabled by default. For other boards, like S3, maybe you need to explicitly opt-in to support versions. We kinda also need this for backwards compatibility anyways. Thanks for all this great feedback, Carl!

**Comment by cboettig** [comment]
:+1: Sounds awesome!

**Comment by javierluraschi** [comment]
Implemented in `pins 0.4` see http://pins.rstudio.com/articles/advanced-versions.html

**Comment by javierluraschi** [comment]
For GitHub specifically, `versions = FALSE` in `board_register()` prevents the package from creating multiple GitHub release files.
