### ISSUE TITLE
minio board

### ISSUE THREAD

**Issue by cboettig** [rstudio/pins#255]
MINIO is an open source implementation that fully implements the Amazon S3 API, so I was wondering if it were possible to use the existing S3 boards with pins?  The only thing that might be necessary is avoiding hardwiring the Amazon host?  It looks like you may already support that but it wasn't quite clear to me how it works.  

> MinIO is a cloud storage server compatible with Amazon S3, released under Apache License v2. 
MinIO <https://min.io/> is "used by the majority of Fortune500 companies"  (Wikipedia).

**Comment by javierluraschi** [comment]
We don't explicitly support MINIO, first time I hear of this; however, since they implement the S3 API it should be really easy to add support. I think the hardest part is probably setting up MINIO locally to validate everything works and potentially a couple tweaks.

I think we would want to copy this file: https://github.com/rstudio/pins/blob/master/R/board_s3.R into `board_minio.R` and match the parameters and add a helper function `board_register_minio()` similar to https://github.com/rstudio/pins/blob/master/R/board_registration.R#L244-L258, that's pretty much it. Bonus points for adding a vignette with a couple screenshots similar to https://github.com/rstudio/pins/blob/master/vignettes/boards-s3.Rmd

Let me know if you are interested in helping out Chris; otherwise, I should be able to take a look in a few weeks, hopefully!

**Comment by cboettig** [comment]
@javierluraschi awesome.  There should be no need to set it up locally if you're all right calling against their existing `play` environment for any tests (see https://docs.min.io/docs/minio-client-quickstart-guide.html)

Yeah, adding it as a separate board might make sense, though I was wondering if it might just work directly with the existing S3 mechanism? (e.g. it's common to just use the `aws-cli` tool to interact with both minio-based and AWS S3 systems...)

**Comment by cboettig** [comment]
@javierluraschi just checking back if you've had a chance to look at this?  I would definitely make use of it but I don't understand enough of the `pins` internals to get you a functional PR...

**Comment by javierluraschi** [comment]
We added support for S3 V4 signatures with https://github.com/rstudio/pins/issues/304 so we are pretty close to enabling MINIO boards; however, I don't believe we will get to this in the short-term unless the community steps in to help. I'm closing this feature but also moved it to the top of our feature requests, see https://github.com/rstudio/pins/projects/1.
