### ISSUE TITLE
Publishing a pin that creates ambiguity fails awkwardly

### ISSUE THREAD

**Issue by colearendt** [rstudio/pins#414]
I just want to be sure this behavior is fixed in the "new" version of pins:

- `user1` publishes a pin to RStudio Connect, let's say `user1/test`
- `user1` makes `user2` a collaborator on `user1/test`
- `user2` publishes a pin named `test`
- The pin "publish" succeeds to `user2/test`, but then `pins` tries to `GET` `test` and fails on ambiguity.

Ideally it would either (1) fail completely - with clear error messaging, or (2) succeed and clearly message that `user2/test` was created

**Comment by hadley** [comment]
`pin_write()` no longer does a `pin_read()` so it succeeds trivially. The next `pin_read()` would still fail though. Is that ok?

**Comment by colearendt** [comment]
Yeah, I think so. So long as the error messaging is clear, that should be fine, I would think. It is unfortunate that namespacing is so ambiguous. 😞

**Comment by loomalaine** [comment]
It would be great to have an option in pin() to return an error if a pin with the same name already exists on the board.

**Comment by hadley** [comment]
@loomalaine that error arises because `pin()` automatically calls `pin_get()` for reasons I don't understand (so it creates a pin with a duplicated name, and then only fails when retrieving it).

What if you just always had to supply the full `user/name` when creating a pin?

**Comment by loomalaine** [comment]
@Hadley Per the last part of my edited comment above (which may have been posted after you read it), the downside to suppling the user is that which member of our team creates the initial pin can vary (in a way that's essentially arbitrary), and since we're using naming conventions that consistent of a standardized name + customer code, keeping track of which user created the pin first for which customer and standardized pin is problematic.

**Comment by loomalaine** [comment]
One solution we've considered for this is use of a team service account to interact with RStudio Connect, so we don't have pins assigned to individuals. The downside to this route where we've gotten some pushback is that we lose the audit trail of who updated what, etc.

**Comment by jpmarindiaz** [comment]
On the other side, it will be dangerous for organizations that don't enforce naming conventions for pins, that is our case. In our case any user should be able to pin and retrieve their own pins, no matter if other users used the same name

**Comment by colearendt** [comment]
A controversial idea that Connect has no idea about, and so gets kinda weird: a "namespaced" option for a board? So you could decide at connection time if the board you are using is namespaced by default or not? And if not, you would be expected to reference pins directly?

**Comment by hadley** [comment]
@colearendt oh I like that — you could do (e.g.) `board_connect(user = "hadley")` and then both `pin_read("foo")` and `pin_write(foo, "foo")` would imply `hadley/foo`.

**Comment by hadley** [comment]
This would be most useful once it was easy to create a project account.

**Comment by hadley** [comment]
Having thought about this more, I think this is currently out of scope for pins — I think the underlying problem is that the ownership model for RSC content isn't quite right. Currently, everything belongs to a specific user, but often you want a pin (or other content type) to belong to a project (which might just be another name for a service account). I think pins behaviour is as good as it can be given the current constraints of RSC, and I'll happily revisit once RSC gets some more flexibility in this area.
