### ISSUE TITLE
Error while reading pin metadata on RStudio Connect

### ISSUE THREAD

**Issue by juliasilge** [rstudio/pins#469]
I am using the current dev version of the package and can use `pin_write()` and `pin_list()` just fine, but am having trouble with `pin_read()` because this line in `pin_meta.pins_board_rsconnect` gives a 404:

https://github.com/rstudio/pins/blob/322b3df464202ef3a4726cded3f1a549cefef11c/R/board_rsconnect.R#L249

``` r
library(pins)

b <- board_rsconnect("envvar")
b %>% pin_read("julia.silge/biv_svm")
#> Error in rsc_check_status(req): Not Found (HTTP 404).
```

<sup>Created on 2021-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

This happens for all pins I try to read. If I try to read again, I get a different error because `data.txt` has been saved with HTML in it.

```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
```

**Comment by andrie** [comment]
The root cause is that the function `board_rsconnect()` constructs the server URL from `hostname` + `__api__`.  However, this ignores the fact that the full domain name can contain `hostname` + `path` + `__api__`.

For example, if the real server is at `colorado.rstudio.com/rsc`, then the API endpoint is at `colorado.rstudio.com/rsc/__api__`, but the current code base ignores the `/rsc` path.

One solution to this is to use `rsconnect::serverInfo()` to construct the URL, like this:

```r
url <- rsconnect::serverInfo(name = server)$url
```

instead of the current:

```r
url <- paste0(server, "/__api__/") # remember to delete this line
```

I'll prepare a PR.
