### ISSUE TITLE
How do you update a pin?

### ISSUE THREAD

**Issue by hadley** [rstudio/pins#6]
Or if `pin()` already lets you overwrite an existing pin, how do you refer to a previous version of the data?

**Comment by iainmwallace** [comment]
In the Connect, it would be very useful to have an option to retrieve a specific "Source Version" of a pin

**Comment by cboettig** [comment]
Also very interested in how this is implemented.  Personally, I'm not sure that it is obvious that pins should be preserving all versions by default.  I often have workflows where I intentionally want to overwrite the previous version, because, say, the new version of the pinned object I've uploaded has just added a single row to some large table, and I don't want the size of my S3 bucket or whatnot to start doubling every time.  

A user can explicitly version a pin manually by doing so in the object name.
