### ISSUE TITLE
Error retrieving pin from Connect board

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pins#94]
Hi,

I am having an issue retrieving pins stored previously on an RStudio Connect board and am unsure how to debug the issue so any pointers greatly received.

I have a shiny app that was working previously now reports that 
Error in board_pin_get.rsconnect(board_get(board), name, ...) : 
  The pin 'my_pin' is not available in the 'rsconnect' board.

In RStudio, I can connect to the board and see that pins name in the connection panel, however when I try to run pin_get(), I receive the same error.

I am able to pin and retrieve a new dataset from the IDE.

Thanks

Iain

**Comment by javierluraschi** [comment]
Hi @iainmwallace, feel free to ping me in [Gitter](https://gitter.im/rstudio/sparklyr?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to fix this real time...

Otherwise, did you upgraded `pins` when this broke or no change was performed?

We had a previous bug that affected RStudio Connect triggered when a pin with a similar name was created, pins would fail to be retrieved, this is already fixed.

So I think on solution is to upgrade `pins` with `remotes::install_github("rstudio/pins")`. For reports that have been already beed published, they would need to be re-published to use the fixed version of pins.

**Comment by iainmwallace** [comment]
Thanks - updating to the latest github version fixed the issue and didn't require republishing the pin.

**Comment by javierluraschi** [comment]
Oh that's great! Hoping we can push a new version to CRAN within a month. If you need this earlier, let is know!
